# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8449591403b3af6b81e674a50c20b9e2bb7ee106a1572fa148b2a4ca5f899da5befaefd49c9b6c116cf831506e1f1942da83cb3700bf0656cadf8f2dd319b53

test:
  secret_key_base: f0bb4f381e03f9dfa2689d0f7b0e24c0a1b1d07fcf7be4912cf309aaa00f6a5245a5fabc0042d9dc5b26a823374b87f823e2d8a348d8b605d2d31456881ea926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
